version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "10:00"
  open-pull-requests-limit: 10
  reviewers:
  - CamiloGarciaLaRotta
  - titoine54
  labels:
  - dependencies
  commit-message:
    prefix: dep
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    time: "10:00"
  open-pull-requests-limit: 10
  reviewers:
  - CamiloGarciaLaRotta
  - titoine54
  labels:
  - dependencies
  commit-message:
    prefix: dep
