name: Build
on: push

jobs:
  build:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - name: Get the sources
        uses: actions/checkout@v3
      - name: Restore the dependencies
        run: npm ci
      - name: Build and Test
        run: npm run all
